### ISSUE TITLE
Fixes and tweaks for the theme

### ISSUE THREAD

**Issue by madsrh** [ubuntu/yaru#1703]
- [X] disabled checkmarks & radio buttons gray 
- [X] change checkmark to Vanilla style 
- [x] Filemenu background should be gray -> #1734 
- [x] hover color for blue checkmark & radio buttons should be more visible
- [x] Remove aubergine from the GDM Cancel button (Shell)
- [x] Yaru 1.0 style tabs
- [x] Menu ~~borders~~ contrast to the area it is drawn on in the dark theme are not strong enough
- [x] 0.5% or 1% lighter buttons (for the headerbar buttons)
- [x] adjust the scale assets to the new colors (also the new focus color ;) )
~~Implement new design for switches~~
Edit by @Feichtmeier : after the design call with mpt we agreed on keeping the switch design as it is
- [x] no borders for checkmarks in file menus and context menus
- [x] grabhandels in the dark theme should be brighter (upstream: https://gitlab.gnome.org/GNOME/gnome-control-center/issues/858, see #1847 for more info)
- [x] Combobox menu’s edges are both 1 pixel too wide -> see #1849 
- [x] Draw a new hand cursor for https://github.com/ubuntu/yaru/issues/855
- [x] NOT-FIXABLE; When a radio menu is opened, the text of the current item should be in the same place.

**Comment by Feichtmeier** [comment]
Eventually the check/radio hover is already fixed
What do you think @madsrh :
Normal:
![image](https://user-images.githubusercontent.com/15329494/72514956-07a04980-3847-11ea-9964-6f4893d8c116.png)
Hover:
![image](https://user-images.githubusercontent.com/15329494/72514997-1b4bb000-3847-11ea-824b-e16508d86f39.png)
![Peek 2020-01-16 10-04](https://user-images.githubusercontent.com/15329494/72515311-957c3480-3847-11ea-9245-4309c5b23835.gif)

**Comment by Amr-Ibra** [comment]
Is this issue on the radar? https://github.com/ubuntu/yaru/issues/1423

**Comment by madsrh** [comment]
@Amr-Ibra yes! Everything is 😄 @ubuntujaggers is currently revisiting the cursor so perhaps he could take a look at this too?

**Comment by clobrano** [comment]
This list comes from the latest design fest, is only a subset of all the open issues and it is by no mean a complete list of goals for 20.04

**Comment by Feichtmeier** [comment]
This issue is mostly about the design fest,... edit: oh nvm look whos there

**Comment by Neocazen** [comment]
Greetings team. Also change the color of the Spinner to orange or purple

**Comment by madsrh** [comment]
I'll close this issue. I've moved the last two open items into separate issues
